name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Publish
        uses: cloudflare/wrangler-action@v3 # Upgraded to v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }} # Moved here from env
          secrets: |
            DISCORD_ROLE_MENTION_ID
            DISCORD_WEBHOOK_URL
        env:
          # These are needed for the Worker to access them at runtime
          DISCORD_ROLE_MENTION_ID: ${{ secrets.DISCORD_ROLE_MENTION_ID }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
